GWT Resouces must be annotated with @Resource annotation
Vertispan/gwt-uibinder pull request #27
Opened 2019-06-10 18:10 UTC by treblereel

2019-06-17 14:54 UTC, jhickman requested changes

2019-06-17 14:54 UTC, jhickman commented on gwt-uibinder-processor/src/main/java/org/gwtproject/uibinder/processor/AbstractFieldWriter.java
> +            System.out.println("find " + getQualifiedSourceName());
Think you left some debugging code in here.   System.out's

2019-06-17 14:54 UTC, jhickman commented on gwt-uibinder-processor/pom.xml
> +    </dependency>
New dependency is unnecessary.   See other comments for replacement expressions.

2019-06-17 14:54 UTC, jhickman commented on gwt-uibinder-processor/src/main/java/org/gwtproject/uibinder/processor/AbstractFieldWriter.java
> +            sb.append(MoreElements.getPackage(element).getQualifiedName().toString());
Can be replaced with:
`sb.append(AptUtil.getPackageElement(element).getQualifiedName().toString())`

2019-06-17 14:54 UTC, jhickman commented on gwt-uibinder-processor/src/main/java/org/gwtproject/uibinder/processor/AbstractFieldWriter.java
> +                  MoreTypes.asElement(type).getModifiers().contains(Modifier.ABSTRACT)) {
Can be replaced with:
`AptUtil.getTypeUtils().asElement(type).getModifiers().contains(Modifier.ABSTRACT)) {`

2019-06-17 14:54 UTC, jhickman commented on gwt-uibinder-processor/src/main/java/org/gwtproject/uibinder/processor/AbstractFieldWriter.java
> +            TypeElement element = (TypeElement)MoreTypes.asElement(type);
This can probably be pulled outside of the `if` statement because line 241 is also converting the TypeMirror to an element.

2019-06-17 14:54 UTC, jhickman commented on gwt-uibinder-processor/src/main/java/org/gwtproject/uibinder/processor/model/HtmlTemplatesWriter.java
> +    if (!UiBinderApiPackage.current().isGwtCreateSupported()) {
For legibility, can you invert the `if` condition?
```
    if (UiBinderApiPackage.current().isGwtCreateSupported()) {
      w.write("Template template = %s.create(Template.class);",
              UiBinderApiPackage.current().getGWTFqn());
    } else {
      w.write("Template template = new %s_TemplateImpl();", outerClassName);
    }
```

2019-06-22 15:59 UTC, treblereel commented
Thanks for your time, updated, could you take a look once again ?

2019-07-16 16:28 UTC, jhickman approved these changes

2019-07-16 16:28 UTC, merged